#!/bin/ksh

#------------------------------
# Print help for master_post.sh
#------------------------------
echo "The script master_post.sh allows the following options:
-h, --help                    Show this help and exit
-g GCM, --gcm GCM             Specify the driving GCM
-x EXP, --exp EXP             Specify the driving experiment name
-s START, --start START       Specify the start for post-processing (format YYYY[MM])
-e END, --end END             Specify the end for post-processing (format YYYY[MM])
--first                       Execute only first script. Second script is skipped.
--second                      Execute only second script. First script is skipped.
-S, --silent                  Reduce printing
-V, --verbose                 Increase printing
-O, --overwrite               Overwrite existing output
--no_batch                    Years are processed sequentially instead of continously starting one-year jobs with sbatch 
--clean                       Remove working directory at the end"



