#!/bin/bash

#
# Burkhardt Rockel / Helmholtz-Zentrum Geesthacht
# Initial Version: 2009/09/02
# Latest Version:  2016/12/16 (Version 2.3)
#

if [[ ${0%/*} == "."  || ${0%/*} == $PWD ]]
then :
else
  echo  === ERROR === subchain must be called from within its directory
  echo "               " it was called from: ${0%/*}
  exit 1
fi

source job_settings

CURRENT_DATE=$(echo ${YDATE_START} | cut -c1-6)
STOP_DATE=$(echo ${YDATE_STOP} | cut -c1-6) #cat ${PFDIR}/date.log | cut -c1-14)
while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
      -g|--gcm)
      GCM=$2
      shift 
      ;;
      -x|--exp)
      EXP=$2
      shift 
      ;;     
       -s|--start)
      CURRENT_DATE=$2
      shift
      ;;
      -e|--end)
      STOP_DATE=$2
      shift 
      ;;
      *)
      echo unknown option!
      ;;  
  esac
  shift 
done

echo "GCM:" ${GCM}
echo "Experiment:" ${EXP}
echo "Start date:" ${CURRENT_DATE}
echo "Stop date:" ${STOP_DATE}


#... experiment identifier

EXPPATH=${GCM}/${EXP}
EXPID=${GCM}_${EXP}

#~ if [ ! -f ${PFDIR}/date.log ]
#~ then
  #~ echo ${YDATE_START} > ${PFDIR}/date.log 
#~ fi

if [ ! -d ${WORKDIR}/${EXPPATH} ]
then
  mkdir -p ${WORKDIR}/${EXPPATH}
fi

### get the current date
#cd ${PFDIR}

INPDIR=${INPUTPOST}/${EXPPATH}
OUTDIR=${OUTPUTPOST}/${EXPPATH}
if [ ! -d ${INPUTPOST}/${EXPPATH} ]
then
  mkdir -p ${INPUTPOST}/${EXPPATH}
fi

YYYY=$(echo ${CURRENT_DATE} | cut -c1-4)
MM=$(echo ${CURRENT_DATE} | cut -c5-6)
MMint=${MM}
if [ $(echo ${MM} | cut -c1) -eq 0 ]
then
  MMint=$(echo ${MMint} | cut -c2  )
fi


#################################################
# Post-processing loop
#################################################

while [ ${CURRENT_DATE} -le ${STOP_DATE} ]
do
  YYYY_MM=${YYYY}_${MM}
  CURRDIR=${YYYY}/output
  if [ ! -d ${INPDIR}/${YYYY} ]
  then
    echo Extracting archive of year ${YYYY}...
    tar -xf ${ARCH_SRC}/${EXPPATH}/*${YYYY}.tar -C ${INPDIR}
    echo Done
  fi
  
  if [ ! -d ${OUTDIR}/${YYYY_MM} ]
  then
    mkdir -p ${OUTDIR}/${YYYY_MM}
  fi

  # build the .job file
  sed \
    -e s%@{CDO}%${CDO}%g \
    -e s%@{CURRENT_DATE}%${CURRENT_DATE}%g \
    -e s%@{EMAIL_ADDRESS}%${EMAIL_ADDRESS}%g \
    -e s%@{EXPID}%${EXPID}%g \
    -e s%@{IE_TOT}%${IE_TOT}%g \
    -e s%@{INPDIR}%${INPDIR}%g \
    -e s%@{ITYPE_COMPRESS_ARCH}%${ITYPE_COMPRESS_ARCH}%g \
    -e s%@{ITYPE_COMPRESS_POST}%${ITYPE_COMPRESS_POST}%g \
    -e s%@{JE_TOT}%${JE_TOT}%g \
    -e s%@{JOBLOGFILE}%${JOBLOGFILE}%g \
    -e s%@{MM}%${MM}%g \
    -e s%@{NBOUNDCUT}%${NBOUNDCUT}%g \
    -e s%@{NC_BINDIR}%${NC_BINDIR}%g \
    -e s%@{NCO_BINDIR}%${NCO_BINDIR}%g \
    -e s%@{NEXT_DATE}%${NEXT_DATE}%g \
    -e s%@{OUTDIR}%${OUTDIR}%g \
    -e s%@{PFDIR}%${PFDIR}%g \
    -e s%@{PROJECT_ACCOUNT}%${PROJECT_ACCOUNT}%g \
    -e s%@{SCRATCHDIR}%${SCRATCHDIR}%g \
    -e s%@{WORKDIR}%${WORKDIR}%g \
    -e s%@{FIRST_YEAR}%${FIRST_YEAR}%g \
    -e s%@{YDATE_START}%${YDATE_START}%g \
    -e s%@{YDATE_STOP}%${YDATE_STOP}%g \
    -e s%@{YYYY_MM}%${YYYY_MM}%g \
    -e s%@{YYYY}%${YYYY}%g \
    -e s%@{CURRDIR}%${CURRDIR}%g \
    -e s%@{EXPPATH}%${EXPPATH}%g \
    <post.job.tmpl>jobs/post${EXPID}.job
  ###  submit the post processing job

  echo *\ submitting POST job for ${YYYY}_${MM} \*

  ${BATCH_CMD} ${PFDIR}/jobs/post${EXPID}.job
  
  MMint=$(python -c "print(int("${MMint}")+1)")
  if [ ${MMint} -ge 13 ]
  then
    MMint=1
    YYYY=$(python -c "print(int("${YYYY}")+1)")
  fi
  
  if [ ${MMint} -le 9 ]
  then
    MM=0${MMint}
  else
    MM=${MMint}
  fi
  
  CURRENT_DATE=${YYYY}${MM}

done
