#!/bin/sh

path="/project/pr04/mgoebel/CMOR/cclm/outputpost/HadGEM2-ES_Hist_RCP85/Hist/timeseries"
DIRS=$(ls ${path})
start=1950
end=1972

fnum=${(( ${end}-${start}+1 ))}
echo ${fnum}
num=0
for d in ${DIRS}
do

num=$(ls ${path}/${d}/ | wc -l)
YY=d | cut -c1-4
if [ ${num} -lt ${fnum} ]
then
echo ${path}/${d}/
echo ${num}
fi

done
